version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"